
import { Metadata } from 'next';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <PrimeReactProvider>
    <html lang="en">
      <head>
    <link id="app-theme" rel="stylesheet" href="/themes/mdc-dark-deeppurple/theme.css"/>
</head>

      <body>{children}</body>
    </html>
    </PrimeReactProvider>
  )
}
